sudo: false
language: node_js
script:
  - npm run build
  - npm run test:ci
node_js:
  - 0.10
  - 2
  - 4
  - 6
  - 8
  - 10
  - 12

matrix:
  include:
    - name: Lint
      node_js: 12
      script: npm run lint
